project:
  type: website
  output-dir: docs

website:
  title: "Ryan Gifford"
  search: 
    location: sidebar
    type: textbox
    
  sidebar:
    style: "docked"
    background: "secondary"
    search: true
    contents:
      - text: "Resume"
        href: index.qmd
      - text: "Interests"
        href: interests.qmd

  navbar:
    search: true
    background: "secondary"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/giffordryan/
      - icon: github
        href: https://github.com/ryangifford

          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

page-footer: "Copyright 2025, Ryan Gifford" 


html:
  style: |
    .ql-heading + hr {
      display: none;
    }

